GET http://localhost:3001/api/variables/compuertas
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxOGU5OTRmZjcxMDI4NTI3YzhjOWY4MSIsInVzZXJuYW1lIjoiZmF1c3RvIiwiaWF0IjoxNjM2NzQ2NzU2fQ.dusS2oygQy4WjnJdr5hre-jb7uW6LRmpmLvoAi3dyKo